
PRG=  misc hanoi philosophers testmath testloops testnondet
PRG+= testconstants testassoc testgcrypt
PRG+= testmagic testaud testvid mp3split
PRG+= testthread1 testthread2 testthread3
PRG+= testlicense testgtk testpix ssim
PRG+= preview-movie iup-simple-notepad
PRG+= testcurl testsqlite3 testwn # testmgl

all:	$(PRG)

clean:
	rm -f *~ *.c *.exe *.txt *.db *.png *.ppm thumbnails.jpg *.zip fractal-tree $(PRG)

misc:		misc.trp
	trpc -f -w misc.trp

hanoi:		hanoi.trp
	trpc -f hanoi.trp

philosophers:	philosophers.trp
	trpc -f philosophers.trp

testmath:	testmath.trp
	trpc -f testmath.trp

testloops:	testloops.trp
	trpc -f testloops.trp

testnondet:	testnondet.trp
	trpc -f testnondet.trp

testconstants:	testconstants.trp
	trpc -f testconstants.trp

testassoc:	testassoc.trp
	trpc -f testassoc.trp

testgcrypt:	testgcrypt.trp
	trpc -f testgcrypt.trp

testmagic:	testmagic.trp
	trpc -f testmagic.trp

testthread1:	testthread1.trp
	trpc -f testthread1.trp

testthread2:	testthread2.trp
	trpc -f testthread2.trp

testthread3:	testthread3.trp
	trpc -f testthread3.trp

testlicense:	testlicense.trp
	trpc -f testlicense.trp

testgtk:	testgtk.trp
	trpc -f testgtk.trp

testpix:	testpix.trp
	trpc -f testpix.trp

ssim:		ssim.trp
	trpc -f ssim.trp

preview-movie:	preview-movie.trp
	trpc -f preview-movie.trp

iup-simple-notepad:	iup-simple-notepad.trp
	trpc -f iup-simple-notepad.trp

testcurl:	testcurl.trp
	trpc -f testcurl.trp

testsqlite3:	testsqlite3.trp
	trpc -f testsqlite3.trp

testaud:	testaud.trp
	trpc -f testaud.trp

testvid:	testvid.trp
	trpc -f testvid.trp

mp3split:	mp3split.trp
	trpc -f mp3split.trp

testwn:		testwn.trp
	trpc -f testwn.trp

testmgl:	testmgl.trp
	trpc -f testmgl.trp

fractal-tree:	fractal-tree.trp
	trpc -f fractal-tree.trp

